create table message (
    id bigint generated by default as identity,
    filename varchar(255),
    tag varchar(255),
    text varchar(255),
    user_id bigint,
    primary key (id));
create table user_role (
    user_id bigint not null,
    roles varchar(255));
create table usr (
    id bigint generated by default as identity,
    activation_code varchar(255),
    active boolean not null,
    email varchar(255),
    password varchar(255),
    username varchar(255),
    primary key (id));
 alter table message
     add constraint message_user_fk
         foreign key (user_id) references usr;
alter table user_role
    add constraint user_role_user_fk
        foreign key (user_id) references usr;
